version: '3.9'

services:
  flask-app:
    container_name: santianalyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/python-docker
    environment:
      - FLASK_ENV=development
    command: [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]
